### ISSUE TITLE
Servants and auto doors

### ISSUE THREAD

**Issue by AnsgarTOdinson** [Kaltharos/AutoCloseDoors#1] opened 2022-08-07 12:07 UTC
Servants routinely make auto doors unable to open.

**Comment by Kaltharos** [comment] 2022-08-07 22:12
I'm not able to reproduce this issue on my test server.
Servants open & close doors normally, and it doesn't make my door stuck.

**Comment by Kaltharos** [comment] 2022-08-08 00:01
Spoke too soon!
Managed to reproduce the issue.

**Comment by Kaltharos** [comment] 2022-08-08 00:08
Fixed in `1.0.2`

**Closed as completed by Kaltharos** 2022-08-08 00:08 UTC
